"""Language and intent data for the NeuroLang emergency assistant."""

INTENT_SYNONYMS = {
    "FOOD": [
        "food",
        "hungry",
        "meal",
        "khana",
        "saapadu",
        "bhojan",
    ],
    "WATER": ["water", "thirsty", "pani", "neer", "jal"],
    "SOS": ["sos", "emergency", "save me", "danger", "help now"],
    "TOILET": ["toilet", "washroom", "restroom", "bathroom", "loo"],
    "PAIN": ["pain", "hurt", "ache", "it hurts", "dukhta", "vali"],
    "MEDICINE": ["medicine", "tablet", "med", "drug", "injection"],
    "HELP": ["help", "assist", "support", "need help"],
    "YES": ["yes", "haan", "aam", "ok", "correct"],
    "NO": ["no", "nah", "not", "wrong", "vendam"],
}

LOCALIZED_OUTPUTS = {
    "en": {
        "FOOD": "I need food, please.",
        "WATER": "I need water, please.",
        "SOS": "Please save me! I need emergency help.",
        "TOILET": "I need to use the toilet.",
        "PAIN": "I am in pain. Please help.",
        "MEDICINE": "I need my medicine, please.",
        "HELP": "Please help me.",
        "YES": "Yes.",
        "NO": "No.",
        "UNKNOWN": "I could not understand. Please try again.",
    },
    "hi": {
        "FOOD": "मुझे खाना चाहिए, कृपया।",
        "WATER": "मुझे पानी चाहिए, कृपया।",
        "SOS": "कृपया बचाइए! आपातकालीन सहायता चाहिए।",
        "TOILET": "मुझे शौचालय जाना है।",
        "PAIN": "मुझे दर्द हो रहा है, कृपया मदद करें।",
        "MEDICINE": "मुझे दवा चाहिए, कृपया।",
        "HELP": "कृपया मेरी मदद करें।",
        "YES": "हाँ।",
        "NO": "नहीं।",
        "UNKNOWN": "मैं समझ नहीं पाया। कृपया दोबारा प्रयास करें।",
    },
    "ta": {
        "FOOD": "எனக்கு உணவு வேண்டும்.",
        "WATER": "எனக்கு தண்ணீர் வேண்டும்.",
        "SOS": "காப்பாற்றுங்கள்! அவசர உதவி தேவை.",
        "TOILET": "எனக்கு கழிப்பறை செல்ல வேண்டும்.",
        "PAIN": "எனக்கு வலி உள்ளது. தயவு செய்து உதவுங்கள்.",
        "MEDICINE": "எனக்கு மருந்து வேண்டும்.",
        "HELP": "தயவு செய்து உதவுங்கள்.",
        "YES": "ஆம்.",
        "NO": "இல்லை.",
        "UNKNOWN": "எனக்கு புரியவில்லை. மீண்டும் முயற்சி செய்யுங்கள்.",
    },
    "te": {
        "FOOD": "నాకు ఆహారం కావాలి.",
        "WATER": "నాకు నీరు కావాలి.",
        "SOS": "దయచేసి రక్షించండి! అత్యవసర సహాయం కావాలి.",
        "TOILET": "నాకు మరుగుదొడ్డి కావాలి.",
        "PAIN": "నాకు నొప్పి ఉంది. దయచేసి సహాయం చేయండి.",
        "MEDICINE": "నాకు మందు కావాలి.",
        "HELP": "దయచేసి సహాయం చేయండి.",
        "YES": "అవును.",
        "NO": "కాదు.",
        "UNKNOWN": "నాకు అర్థం కాలేదు. మళ్లీ ప్రయత్నించండి.",
    },
}
